// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Bots.
    /// </summary>
    public static partial class BotsExtensions
    {
            /// <summary>
            /// Gets information about a bot user.
            /// <see href="https://api.slack.com/methods/bots.info" />
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='token'>
            /// Authentication token. Requires scope: `users:read`
            /// </param>
            /// <param name='bot'>
            /// Bot user to get info on
            /// </param>
            public static InfoOKResponseModel Info(this IBots operations, string token = default(string), string bot = default(string))
            {
                return operations.InfoAsync(token, bot).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Gets information about a bot user.
            /// <see href="https://api.slack.com/methods/bots.info" />
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='token'>
            /// Authentication token. Requires scope: `users:read`
            /// </param>
            /// <param name='bot'>
            /// Bot user to get info on
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<InfoOKResponseModel> InfoAsync(this IBots operations, string token = default(string), string bot = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.InfoWithHttpMessagesAsync(token, bot, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
