// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Migration operations.
    /// </summary>
    public partial interface IMigration
    {
        /// <summary>
        /// For Enterprise Grid workspaces, map local user IDs to global user
        /// IDs
        /// <see href="https://api.slack.com/methods/migration.exchange" />
        /// </summary>
        /// <param name='token'>
        /// Authentication token. Requires scope: `tokens.basic`
        /// </param>
        /// <param name='toOld'>
        /// Specify `true` to convert `W` global user IDs to workspace-specific
        /// `U` IDs. Defaults to `false`.
        /// </param>
        /// <param name='users'>
        /// A comma-separated list of user ids, up to 400 per request
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="ExchangeErrorModelException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        Task<HttpOperationResponse<ExchangeOKResponse>> ExchangeWithHttpMessagesAsync(string token = default(string), bool? toOld = default(bool?), string users = default(string), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
