// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InfoOKResponseBotIcons
    {
        /// <summary>
        /// Initializes a new instance of the InfoOKResponseBotIcons class.
        /// </summary>
        public InfoOKResponseBotIcons()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InfoOKResponseBotIcons class.
        /// </summary>
        public InfoOKResponseBotIcons(string image36, string image48, string image72)
        {
            Image36 = image36;
            Image48 = image48;
            Image72 = image72;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_36")]
        public string Image36 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_48")]
        public string Image48 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_72")]
        public string Image72 { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Image36 == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Image36");
            }
            if (Image48 == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Image48");
            }
            if (Image72 == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Image72");
            }
        }
    }
}
