// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// bots.info schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from bots.info method
    /// </remarks>
    public partial class InfoOKResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the InfoOKResponseModel class.
        /// </summary>
        public InfoOKResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InfoOKResponseModel class.
        /// </summary>
        public InfoOKResponseModel(InfoOKResponseBot bot)
        {
            Bot = bot;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for InfoOKResponseModel class.
        /// </summary>
        static InfoOKResponseModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bot")]
        public InfoOKResponseBot Bot { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Bot == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Bot");
            }
            if (Bot != null)
            {
                Bot.Validate();
            }
        }
    }
}
