// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// conversations.join success schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from conversations.join method
    /// </remarks>
    public partial class JoinOKResponseModel
    {
        /// <summary>
        /// Initializes a new instance of the JoinOKResponseModel class.
        /// </summary>
        public JoinOKResponseModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the JoinOKResponseModel class.
        /// </summary>
        /// <param name="responseMetadata">Response metadata</param>
        public JoinOKResponseModel(object channel, JoinOKResponseResponseMetadata responseMetadata = default(JoinOKResponseResponseMetadata), string warning = default(string))
        {
            Channel = channel;
            ResponseMetadata = responseMetadata;
            Warning = warning;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for JoinOKResponseModel class.
        /// </summary>
        static JoinOKResponseModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channel")]
        public object Channel { get; set; }

        /// <summary>
        /// Gets or sets response metadata
        /// </summary>
        [JsonProperty(PropertyName = "response_metadata")]
        public JoinOKResponseResponseMetadata ResponseMetadata { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "warning")]
        public string Warning { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Channel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Channel");
            }
            if (ResponseMetadata != null)
            {
                ResponseMetadata.Validate();
            }
        }
    }
}
