// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// files.list schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from files.list method
    /// </remarks>
    public partial class ListOKResponseModelModelModelModelModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ListOKResponseModelModelModelModelModel class.
        /// </summary>
        public ListOKResponseModelModelModelModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ListOKResponseModelModelModelModelModel class.
        /// </summary>
        public ListOKResponseModelModelModelModelModel(IList<ObjsFile> files, ObjsPaging paging)
        {
            Files = files;
            Paging = paging;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for ListOKResponseModelModelModelModelModel
        /// class.
        /// </summary>
        static ListOKResponseModelModelModelModelModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "files")]
        public IList<ObjsFile> Files { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "paging")]
        public ObjsPaging Paging { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Files == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Files");
            }
            if (Paging == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Paging");
            }
            if (Files != null)
            {
                if (Files.Count < 0)
                {
                    throw new ValidationException(ValidationRules.MinItems, "Files", 0);
                }
                if (Files.Count != System.Linq.Enumerable.Count(System.Linq.Enumerable.Distinct(Files)))
                {
                    throw new ValidationException(ValidationRules.UniqueItems, "Files");
                }
                foreach (var element in Files)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (Paging != null)
            {
                Paging.Validate();
            }
        }
    }
}
