// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// users.list schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from users.list method
    /// </remarks>
    public partial class ListOKResponseModelModelModelModelModelModelModelModelModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ListOKResponseModelModelModelModelModelModelModelModelModel class.
        /// </summary>
        public ListOKResponseModelModelModelModelModelModelModelModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ListOKResponseModelModelModelModelModelModelModelModelModel class.
        /// </summary>
        public ListOKResponseModelModelModelModelModelModelModelModelModel(int cacheTs, IList<ObjsUser> members)
        {
            CacheTs = cacheTs;
            Members = members;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for
        /// ListOKResponseModelModelModelModelModelModelModelModelModel class.
        /// </summary>
        static ListOKResponseModelModelModelModelModelModelModelModelModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cache_ts")]
        public int CacheTs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "members")]
        public IList<ObjsUser> Members { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Members == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Members");
            }
            if (Members != null)
            {
                if (Members.Count < 1)
                {
                    throw new ValidationException(ValidationRules.MinItems, "Members", 1);
                }
                if (Members.Count != System.Linq.Enumerable.Count(System.Linq.Enumerable.Distinct(Members)))
                {
                    throw new ValidationException(ValidationRules.UniqueItems, "Members");
                }
                foreach (var element in Members)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
