// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// conversations.members success schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response conversations.members method
    /// </remarks>
    public partial class MembersOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the MembersOKResponse class.
        /// </summary>
        public MembersOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MembersOKResponse class.
        /// </summary>
        public MembersOKResponse(IList<string> members, MembersOKResponseResponseMetadata responseMetadata)
        {
            Members = members;
            ResponseMetadata = responseMetadata;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for MembersOKResponse class.
        /// </summary>
        static MembersOKResponse()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "members")]
        public IList<string> Members { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "response_metadata")]
        public MembersOKResponseResponseMetadata ResponseMetadata { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Members == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Members");
            }
            if (ResponseMetadata == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ResponseMetadata");
            }
            if (Members != null)
            {
                if (Members.Count < 1)
                {
                    throw new ValidationException(ValidationRules.MinItems, "Members", 1);
                }
                if (Members.Count != System.Linq.Enumerable.Count(System.Linq.Enumerable.Distinct(Members)))
                {
                    throw new ValidationException(ValidationRules.UniqueItems, "Members");
                }
            }
            if (ResponseMetadata != null)
            {
                ResponseMetadata.Validate();
            }
        }
    }
}
