// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ObjsTeamIcon
    {
        /// <summary>
        /// Initializes a new instance of the ObjsTeamIcon class.
        /// </summary>
        public ObjsTeamIcon()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ObjsTeamIcon class.
        /// </summary>
        public ObjsTeamIcon(string image102 = default(string), string image132 = default(string), string image230 = default(string), string image34 = default(string), string image44 = default(string), string image68 = default(string), string image88 = default(string), bool? imageDefault = default(bool?))
        {
            Image102 = image102;
            Image132 = image132;
            Image230 = image230;
            Image34 = image34;
            Image44 = image44;
            Image68 = image68;
            Image88 = image88;
            ImageDefault = imageDefault;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_102")]
        public string Image102 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_132")]
        public string Image132 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_230")]
        public string Image230 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_34")]
        public string Image34 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_44")]
        public string Image44 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_68")]
        public string Image68 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_88")]
        public string Image88 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image_default")]
        public bool? ImageDefault { get; set; }

    }
}
