// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ObjsMessageRepliesItem
    {
        /// <summary>
        /// Initializes a new instance of the ObjsMessageRepliesItem class.
        /// </summary>
        public ObjsMessageRepliesItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ObjsMessageRepliesItem class.
        /// </summary>
        public ObjsMessageRepliesItem(string ts, string user)
        {
            Ts = ts;
            User = user;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ts")]
        public string Ts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "user")]
        public string User { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Ts == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ts");
            }
            if (User == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "User");
            }
        }
    }
}
