// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// mpim.open success schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from mpim.open method
    /// </remarks>
    public partial class OpenOKResponseModelModelModel
    {
        /// <summary>
        /// Initializes a new instance of the OpenOKResponseModelModelModel
        /// class.
        /// </summary>
        public OpenOKResponseModelModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OpenOKResponseModelModelModel
        /// class.
        /// </summary>
        public OpenOKResponseModelModelModel(ObjsGroup group)
        {
            Group = group;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for OpenOKResponseModelModelModel class.
        /// </summary>
        static OpenOKResponseModelModelModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "group")]
        public ObjsGroup Group { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Group == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Group");
            }
            if (Group != null)
            {
                Group.Validate();
            }
        }
    }
}
