// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// im.open success schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from im.open method
    /// </remarks>
    public partial class OpenOKResponseModelModel
    {
        /// <summary>
        /// Initializes a new instance of the OpenOKResponseModelModel class.
        /// </summary>
        public OpenOKResponseModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OpenOKResponseModelModel class.
        /// </summary>
        public OpenOKResponseModelModel(OpenOKResponseChannel channel, bool? alreadyOpen = default(bool?), bool? noOp = default(bool?))
        {
            AlreadyOpen = alreadyOpen;
            Channel = channel;
            NoOp = noOp;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for OpenOKResponseModelModel class.
        /// </summary>
        static OpenOKResponseModelModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "already_open")]
        public bool? AlreadyOpen { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channel")]
        public OpenOKResponseChannel Channel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "no_op")]
        public bool? NoOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Channel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Channel");
            }
            if (Channel != null)
            {
                Channel.Validate();
            }
        }
    }
}
