// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// chat.postMessage error schema
    /// </summary>
    /// <remarks>
    /// Schema for error response chat.postMessage method
    /// </remarks>
    public partial class PostMessageErrorModel
    {
        /// <summary>
        /// Initializes a new instance of the PostMessageErrorModel class.
        /// </summary>
        public PostMessageErrorModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostMessageErrorModel class.
        /// </summary>
        /// <param name="error">Possible values include: 'channel_not_found',
        /// 'not_in_channel', 'is_archived', 'msg_too_long', 'no_text',
        /// 'too_many_attachments', 'rate_limited', 'not_authed',
        /// 'invalid_auth', 'account_inactive', 'invalid_arg_name',
        /// 'invalid_array_arg', 'invalid_charset', 'invalid_form_data',
        /// 'invalid_post_type', 'missing_post_type'</param>
        public PostMessageErrorModel(string error)
        {
            Error = error;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for PostMessageErrorModel class.
        /// </summary>
        static PostMessageErrorModel()
        {
            Ok = false;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'channel_not_found',
        /// 'not_in_channel', 'is_archived', 'msg_too_long', 'no_text',
        /// 'too_many_attachments', 'rate_limited', 'not_authed',
        /// 'invalid_auth', 'account_inactive', 'invalid_arg_name',
        /// 'invalid_array_arg', 'invalid_charset', 'invalid_form_data',
        /// 'invalid_post_type', 'missing_post_type'
        /// </summary>
        [JsonProperty(PropertyName = "error")]
        public string Error { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Error == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Error");
            }
        }
    }
}
