// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// chat.postMessage success schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response of chat.postMessage method
    /// </remarks>
    public partial class PostMessageOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the PostMessageOKResponse class.
        /// </summary>
        public PostMessageOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostMessageOKResponse class.
        /// </summary>
        public PostMessageOKResponse(string channel, ObjsMessage message, string ts)
        {
            Channel = channel;
            Message = message;
            Ts = ts;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for PostMessageOKResponse class.
        /// </summary>
        static PostMessageOKResponse()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channel")]
        public string Channel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public ObjsMessage Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ts")]
        public string Ts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Channel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Channel");
            }
            if (Message == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Message");
            }
            if (Ts == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Ts");
            }
            if (Message != null)
            {
                Message.Validate();
            }
        }
    }
}
