// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PrefsPrefsLocalesEnabled
    {
        /// <summary>
        /// Initializes a new instance of the PrefsPrefsLocalesEnabled class.
        /// </summary>
        public PrefsPrefsLocalesEnabled()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PrefsPrefsLocalesEnabled class.
        /// </summary>
        public PrefsPrefsLocalesEnabled(string deDE = default(string), string enUS = default(string), string esES = default(string), string frFR = default(string), string jaJP = default(string), string pseudo = default(string))
        {
            DeDE = deDE;
            EnUS = enUS;
            EsES = esES;
            FrFR = frFR;
            JaJP = jaJP;
            Pseudo = pseudo;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "de-DE")]
        public string DeDE { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "en-US")]
        public string EnUS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "es-ES")]
        public string EsES { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fr-FR")]
        public string FrFR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ja-JP")]
        public string JaJP { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pseudo")]
        public string Pseudo { get; set; }

    }
}
