// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// channels.rename schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from channels.rename method
    /// </remarks>
    public partial class RenameOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the RenameOKResponse class.
        /// </summary>
        public RenameOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RenameOKResponse class.
        /// </summary>
        public RenameOKResponse(ObjsChannel channel)
        {
            Channel = channel;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for RenameOKResponse class.
        /// </summary>
        static RenameOKResponse()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "channel")]
        public ObjsChannel Channel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Channel == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Channel");
            }
            if (Channel != null)
            {
                Channel.Validate();
            }
        }
    }
}
