// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// users.profile.set schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from users.profile.set method
    /// </remarks>
    public partial class SetOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the SetOKResponse class.
        /// </summary>
        public SetOKResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SetOKResponse class.
        /// </summary>
        public SetOKResponse(ObjsUserProfile profile, string username)
        {
            Profile = profile;
            Username = username;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for SetOKResponse class.
        /// </summary>
        static SetOKResponse()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "profile")]
        public ObjsUserProfile Profile { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Profile == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Profile");
            }
            if (Username == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Username");
            }
            if (Profile != null)
            {
                Profile.Validate();
            }
        }
    }
}
