// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// groups.setTopic schema
    /// </summary>
    /// <remarks>
    /// Schema for successful response from groups.setTopic method
    /// </remarks>
    public partial class SetTopicOKResponseModelModel
    {
        /// <summary>
        /// Initializes a new instance of the SetTopicOKResponseModelModel
        /// class.
        /// </summary>
        public SetTopicOKResponseModelModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SetTopicOKResponseModelModel
        /// class.
        /// </summary>
        public SetTopicOKResponseModelModel(string topic)
        {
            Topic = topic;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for SetTopicOKResponseModelModel class.
        /// </summary>
        static SetTopicOKResponseModelModel()
        {
            Ok = true;
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "topic")]
        public string Topic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ok")]
        public static bool Ok { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Topic == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Topic");
            }
        }
    }
}
