// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Slack.Api.CSharp.WebApi.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TeamPrefsPrefsWhoCanManageSharedChannels
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TeamPrefsPrefsWhoCanManageSharedChannels class.
        /// </summary>
        public TeamPrefsPrefsWhoCanManageSharedChannels()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// TeamPrefsPrefsWhoCanManageSharedChannels class.
        /// </summary>
        public TeamPrefsPrefsWhoCanManageSharedChannels(IList<string> type)
        {
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public IList<string> Type { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Type == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Type");
            }
        }
    }
}
